import re


def build_comic_layout(image_paths: list, full_story: str, outline: list) -> list:
    """
    Organizes the generated images and full comic story into a structured layout.

    Args:
        image_paths (list): File paths of generated images for each panel.
        full_story (str): Full story narration text generated by Gemini Pro.
        outline (list): Structured panel outline dictionaries from Gemini Flash.

    Returns:
        list: A list of dictionaries containing panel number, title, image_path, text, and scene_description.
    """
    # Split the full story into individual panel segments
    story_panels = full_story.split("**Panel")
    story_panels = [
        f"**Panel{panel}"
        for panel in story_panels
        if panel.strip() and re.match(r"^\s*\d+", panel)
    ]

    # Fallback if the LLM omitted asterisks around 'Panel X'
    if len(story_panels) < len(outline):
        alt_splits = re.split(r"(?=(?:^|\n)#*\s*\**Panel\s+\d+)", full_story)
        alt_panels = [
            chunk.strip()
            for chunk in alt_splits
            if re.search(r"Panel\s+\d+", chunk)
        ]
        if len(alt_panels) >= len(story_panels):
            story_panels = alt_panels

    # Pad story_panels if fewer segments were returned than outline panels
    while len(story_panels) < len(outline):
        idx = len(story_panels)
        fallback_desc = outline[idx].get("scene_description", "")
        story_panels.append(f"**Panel {idx + 1}**\n{fallback_desc}")

    # Build layout panel by panel
    layout = []
    for idx, (image, text, panel_info) in enumerate(zip(image_paths, story_panels, outline), start=1):
        lines = text.strip().splitlines()
        body_text = "\n".join(lines[1:]).strip() if len(lines) > 1 else text.strip()

        layout.append({
            "panel": idx,
            "title": panel_info.get("title", f"Panel {idx}"),
            "image_path": image.replace("\\", "/"),
            "text": body_text,  # remove panel title line
            "scene_description": panel_info.get("scene_description", ""),
            "image_prompt": panel_info.get("image_prompt", "")
        })

    return layout